<?php

namespace MK\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getTotal()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $expr = $queryBuilder->expr();
        $queryBuilder->select($expr->count('p.id'));
        $result = $queryBuilder->getQuery()->getSingleScalarResult();
        
        return $result;
    }
}
