<?php

namespace MK\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductColorRepository extends EntityRepository
{
}
