security:
    providers:
        administrators:
            entity: { class: MKUserBundle:User, property: username }  
        in_memory:
            memory: 
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    #admin: { password: admin, roles: 'ROLE_ADMIN' }
                  
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MK\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        no_secure_area:
            pattern: ^/admin/login$
            anonymous:  ~
            
        admin_area:
            pattern:   ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin 
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   /admin/logout
                target: /admin/login    